### ISSUE TITLE
A version for MGN9 rails?

### ISSUE THREAD

**Issue by jamincollins** [Driftrotor/Voron-V0.2r1-Double-Shear-AB-Motor-Mounts#1]
Any chance you could make (or tweak) a version to allow for MGN9 rails (more specifically the carriage)?

**Comment by Driftrotor** [comment]
yes this has been a bit on the back burner for a while but i can make this happen soon for you.
have you thought about Tulip mod?
this already has MGN9 compatibility and addresses some weak points in this design.
https://github.com/Amekyras/tulip

**Comment by jamincollins** [comment]
I was not aware of that mod. Please consider this resolved.
